---
title: "QuickBLAST"
#output: rmarkdown::html_vignette
author: "Vishvesh Karthik"
date: "`r Sys.Date()`"
urlcolor: blue
output:
  rmarkdown::html_vignette:
    highlight: espresso
    self_contained: true
#theme: flatly
    wrap: 60
    columns: 60
    toc: true
    toc_depth: 4
    # toc_float:
      # collapsed: true
    number_sections: true
vignette: >
  %\VignetteIndexEntry{QuickBLAST}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

---
title: "Introduction to QuickBLAST"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, echo=TRUE,include=T, tidy=TRUE}
library(QuickBLAST)
QuickBLAST::isQuickBLASTLoaded()
blastp_inst <- QuickBLAST::CreateQuickBLASTInstance(seq_type = 1, strand = 0, program = "blastp", save_sequences = TRUE, options = "-evalue 100000")
blastn_inst <- QuickBLAST::CreateQuickBLASTInstance(seq_type = 0, strand = 0, program = "blastn", options = "-evalue 100000")
tblastx_inst <- QuickBLAST::CreateQuickBLASTInstance(seq_type = 0, strand = 0, program = "tblastx")
blastp_inst
blastn_inst
tblastx_inst
```

```{r inst_man, echo=TRUE,include=T, tidy=TRUE}
QuickBLAST::GetInstanceCount()
QuickBLAST::GetInstanceID(blastp_inst)
QuickBLAST::GetInstanceID(blastn_inst)
QuickBLAST::GetInstanceID(tblastx_inst)
QuickBLAST::GetQuickBLASTInstance(0)
QuickBLAST::GetQuickBLASTInstance(1)
QuickBLAST::GetQuickBLASTInstance(2)
identical(QuickBLAST::GetQuickBLASTInstance(0), blastp_inst)
identical(QuickBLAST::GetQuickBLASTInstance(1), blastn_inst)
identical(QuickBLAST::GetQuickBLASTInstance(2), tblastx_inst)
identical(QuickBLAST::GetQuickBLASTInstance(0), tblastx_inst)
QuickBLAST::DeleteQuickBLASTInstance(QuickBLAST::GetQuickBLASTInstance(1))
QuickBLAST::DeleteQuickBLASTInstance(2)
QuickBLAST::GetInstanceCount()
QuickBLAST::GetQuickBLASTInstance(0)
try(identical(QuickBLAST::GetQuickBLASTInstance(1), blastn_inst))
blastn_inst <- QuickBLAST::CreateQuickBLASTInstance(seq_type = 0, strand = 0, program = "blastn")
```


```{r test}
QuickBLAST::BLAST2Seqs(tblastx_inst, "AAAAAAAAAAAATTTTTTTTTTTTGGGGGGGGGGGCCCCCCCCC", "TTTTTTTTTTTGGGGGGGGGGGG")
try(QuickBLAST::BLAST2Seqs(blastn_inst, "AAAAAAAAAAAATTTTTTTTTTTTGGGGGGGGGGGCCCCCCCCC", "TTTTTTTTTTTGGGGGGGGGGGG"))
try(QuickBLAST::BLAST2Seqs(blastp_inst, "AAAAAAAAAAAATTTTTTTTTTTTGGGGGGGGGGGCCCCCCCCC", "TTTTTTTTTTTGGGGGGGGGGGG"))
try(QuickBLAST::BLAST2Seqs(blastp_inst, "MQILLVEDDNTLFQELKKELEQWDFNVAGIEDFGKVMDTFESFNPEIVILDVQLPKYDGFYWCRKMREVSNVPILFLSSRDNPMDQVMSMELGADDYMQKPFYTNVLIAKLQAIYRRVYEFTAEEKRTLTWQDAVVDLSKDSIQKGDDTIFLSKTEMIILEILITKKNQIVSRDTIITALWDDEAFVSDNTLTVNVNRLRKKLSEISMDSAIETKVGKGYMAHE", "MQILLVEDDNTLFQELKKELEQWDFNVAGIEDFGKVMDTFESFNPEIVILDVQLPKYDGFYWCRKMREVSNVPILFLSSRDNPMDQVMSMELGADDYMQKPFYTNVLIAKLQAIYRRVYEFTAEEKRTLTWQDAVVDLSKDSIQKGDDTIFLSKTEMIILEILITKKNQIVSRDTIITALWDDEAFVSDNTLTVNVNRLRKKLSEISMDSAIETKVGKGYMAHE"))
try(QuickBLAST::RemoteBLAST(blastn_inst, query_input="AAAAAAAAAAAATTTTTTTTTTTTGGGGGGGGGGGCCCCCCCCC", database= "nr", input_type=1, return_values=T))

try(QuickBLAST::RemoteBLAST(blastp_inst, query_input="MQILLVEDDNTLFQELKKELEQWDFNVAGIEDFGKVMDTFESFNPEIVILDVQLPKYDGFYWCRKMREVSNVPILFLSSRDNPMDQVMSMELGADDYMQKPFYTNVLIAKLQAIYRRVYEFTAEEKRTLTWQDAVVDLSKDSIQKGDDTIFLSKTEMIILEILITKKNQIVSRDTIITALWDDEAFVSDNTLTVNVNRLRKKLSEISMDSAIETKVGKGYMAHE", database= "pdb", input_type=1, return_values=T))
```