#Set NCBI Components which give issues during build
# DO NOT print messages here as this is included with the toolchain and will plague the output, only print for DEBUGGING

if(NOT NCBITK_ROOT_DIR)
    set(NCBITK_ROOT_DIR $ENV{NCBITK_ROOT_DIR})
endif(NOT NCBITK_ROOT_DIR)

#lmdb
if(NOT NCBI_COMPONENT_LMDB_FOUND AND NOT HAVE_LIBLMDB)
    set(NCBI_COMPONENT_LocalLMDB_FOUND LOCAL)
    set(NCBI_COMPONENT_LocalLMDB_INCLUDE ${NCBITK_ROOT_DIR}/include/util/lmdb)
    set(NCBI_COMPONENT_LocalLMDB_NCBILIB lmdb)
    set(NCBI_COMPONENT_LMDB_FOUND ${NCBI_COMPONENT_LocalLMDB_FOUND})
    set(NCBI_COMPONENT_LMDB_INCLUDE ${NCBI_COMPONENT_LocalLMDB_INCLUDE})
    set(NCBI_COMPONENT_LMDB_NCBILIB ${NCBI_COMPONENT_LocalLMDB_NCBILIB})
    set(HAVE_LIBLMDB ${NCBI_COMPONENT_LMDB_FOUND})
endif()