#Set NCBI Components which give issues during build
# DO NOT print messages here as this is included with the toolchain and will plague the output, only print for DEBUGGING

if(NOT NCBITK_ROOT_DIR)
    set(NCBITK_ROOT_DIR $ENV{NCBITK_ROOT_DIR})
endif(NOT NCBITK_ROOT_DIR)

#lmdb
if(NOT NCBI_COMPONENT_LMDB_FOUND AND NOT HAVE_LIBLMDB)
    set(NCBI_COMPONENT_LocalLMDB_FOUND LOCAL)
    set(NCBI_COMPONENT_LocalLMDB_INCLUDE ${NCBITK_ROOT_DIR}/include/util/lmdb)
    set(NCBI_COMPONENT_LocalLMDB_NCBILIB lmdb)
    set(NCBI_COMPONENT_LMDB_FOUND ${NCBI_COMPONENT_LocalLMDB_FOUND})
    set(NCBI_COMPONENT_LMDB_INCLUDE ${NCBI_COMPONENT_LocalLMDB_INCLUDE})
    set(NCBI_COMPONENT_LMDB_NCBILIB ${NCBI_COMPONENT_LocalLMDB_NCBILIB})
    set(HAVE_LIBLMDB ${NCBI_COMPONENT_LMDB_FOUND})
endif()

#sqlite
# Use CMAKE_CURRENT_LIST_DIR to reliably get the toolkit root directory
get_filename_component(QUICKBLAST_BUILD_DIR "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(CUSTOM_SQLITE_DIR "${QUICKBLAST_BUILD_DIR}/sqlite")
set(CUSTOM_SQLITE_LIB "${CUSTOM_SQLITE_DIR}/libsqlite3.a")

if(EXISTS "${CUSTOM_SQLITE_LIB}")
    # Override NCBI Component Variables
    set(NCBI_COMPONENT_SQLITE3_FOUND YES CACHE INTERNAL "Forced SQLite3" FORCE)
    set(NCBI_COMPONENT_SQLITE3_INCLUDE "${CUSTOM_SQLITE_DIR}" CACHE INTERNAL "Forced SQLite Include" FORCE)
    set(NCBI_COMPONENT_SQLITE3_LIBS "${CUSTOM_SQLITE_LIB}" CACHE INTERNAL "Forced SQLite Lib" FORCE)
    set(NCBI_COMPONENT_SQLITE3_DEFINES "" CACHE INTERNAL "Forced SQLite Defines" FORCE)
    
    # Override Standard CMake Find variables just in case
    set(SQLITE3_FOUND YES CACHE INTERNAL "Forced SQLite3" FORCE)
    set(SQLITE3_INCLUDE_DIR "${CUSTOM_SQLITE_DIR}" CACHE INTERNAL "Forced SQLite Include" FORCE)
    set(SQLITE3_LIBRARY "${CUSTOM_SQLITE_LIB}" CACHE INTERNAL "Forced SQLite Lib" FORCE)
    set(SQLite3_LIBRARY "${CUSTOM_SQLITE_LIB}" CACHE INTERNAL "Forced SQLite Lib" FORCE)
    
    set(HAVE_LIBSQLITE3 YES CACHE INTERNAL "Forced SQLite3" FORCE)
else()
    message(FATAL_ERROR "Custom SQLite lib NOT FOUND at: ${CUSTOM_SQLITE_LIB}")
endif()