cat(paste("INSTALLING....", R_PACKAGE_NAME, sep=""))
# cat(R_PACKAGE_DIR)
# cat(R_PACKAGE_SOURCE)
files <- c(Sys.glob(paste0(file.path(R_PACKAGE_SOURCE,"inst"), SHLIB_EXT)),Sys.glob(paste0("*", SHLIB_EXT)))
dest <- file.path(R_PACKAGE_DIR, paste0('libs', R_ARCH))
dir.create(dest, recursive = TRUE, showWarnings = FALSE)
file.copy(files, dest, overwrite = TRUE)
if(file.exists("symbols.rds"))
    file.copy("symbols.rds", dest, overwrite = TRUE)