// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// isQuickBLASTLoaded
SEXP isQuickBLASTLoaded();
RcppExport SEXP _QuickBLAST_isQuickBLASTLoaded() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(isQuickBLASTLoaded());
    return rcpp_result_gen;
END_RCPP
}
// GetInstanceCount
SEXP GetInstanceCount();
RcppExport SEXP _QuickBLAST_GetInstanceCount() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(GetInstanceCount());
    return rcpp_result_gen;
END_RCPP
}
// CreateNewBLASTInstance
SEXP CreateNewBLASTInstance(SEXP seq_info, SEXP program, SEXP options);
RcppExport SEXP _QuickBLAST_CreateNewBLASTInstance(SEXP seq_infoSEXP, SEXP programSEXP, SEXP optionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type seq_info(seq_infoSEXP);
    Rcpp::traits::input_parameter< SEXP >::type program(programSEXP);
    Rcpp::traits::input_parameter< SEXP >::type options(optionsSEXP);
    rcpp_result_gen = Rcpp::wrap(CreateNewBLASTInstance(seq_info, program, options));
    return rcpp_result_gen;
END_RCPP
}
