// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppThread.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// isQuickBLASTLoaded
RcppExport bool isQuickBLASTLoaded();
RcppExport SEXP _QuickBLAST_isQuickBLASTLoaded() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(isQuickBLASTLoaded());
    return rcpp_result_gen;
END_RCPP
}
// RecordBatchVectorToFlattenedDFList
Rcpp::List RecordBatchVectorToFlattenedDFList(SEXP rbv_sexp);
RcppExport SEXP _QuickBLAST_RecordBatchVectorToFlattenedDFList(SEXP rbv_sexpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type rbv_sexp(rbv_sexpSEXP);
    rcpp_result_gen = Rcpp::wrap(RecordBatchVectorToFlattenedDFList(rbv_sexp));
    return rcpp_result_gen;
END_RCPP
}
// CreateQuickBLASTInstance
RcppExport SEXP CreateQuickBLASTInstance(const int seq_type, const int strand, SEXP program, SEXP options, const bool save_sequences, const bool save_hsp_sequences);
RcppExport SEXP _QuickBLAST_CreateQuickBLASTInstance(SEXP seq_typeSEXP, SEXP strandSEXP, SEXP programSEXP, SEXP optionsSEXP, SEXP save_sequencesSEXP, SEXP save_hsp_sequencesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type seq_type(seq_typeSEXP);
    Rcpp::traits::input_parameter< const int >::type strand(strandSEXP);
    Rcpp::traits::input_parameter< SEXP >::type program(programSEXP);
    Rcpp::traits::input_parameter< SEXP >::type options(optionsSEXP);
    Rcpp::traits::input_parameter< const bool >::type save_sequences(save_sequencesSEXP);
    Rcpp::traits::input_parameter< const bool >::type save_hsp_sequences(save_hsp_sequencesSEXP);
    rcpp_result_gen = Rcpp::wrap(CreateQuickBLASTInstance(seq_type, strand, program, options, save_sequences, save_hsp_sequences));
    return rcpp_result_gen;
END_RCPP
}
// GetInstanceCount
RcppExport unsigned int GetInstanceCount();
RcppExport SEXP _QuickBLAST_GetInstanceCount() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(GetInstanceCount());
    return rcpp_result_gen;
END_RCPP
}
// GetInstanceID
RcppExport SEXP GetInstanceID(SEXP ptr);
RcppExport SEXP _QuickBLAST_GetInstanceID(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(GetInstanceID(ptr));
    return rcpp_result_gen;
END_RCPP
}
// GetQuickBLASTInstance
RcppExport SEXP GetQuickBLASTInstance(unsigned int ptr_id);
RcppExport SEXP _QuickBLAST_GetQuickBLASTInstance(SEXP ptr_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type ptr_id(ptr_idSEXP);
    rcpp_result_gen = Rcpp::wrap(GetQuickBLASTInstance(ptr_id));
    return rcpp_result_gen;
END_RCPP
}
// DeleteQuickBLASTInstance
RcppExport SEXP DeleteQuickBLASTInstance(SEXP ptr);
RcppExport SEXP _QuickBLAST_DeleteQuickBLASTInstance(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(DeleteQuickBLASTInstance(ptr));
    return rcpp_result_gen;
END_RCPP
}
// GetQuickBLASTOptions
RcppExport SEXP GetQuickBLASTOptions(SEXP ptr);
RcppExport SEXP _QuickBLAST_GetQuickBLASTOptions(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(GetQuickBLASTOptions(ptr));
    return rcpp_result_gen;
END_RCPP
}
// SetQuickBLASTOptions
RcppExport bool SetQuickBLASTOptions(SEXP ptr, SEXP program_name, SEXP options, bool verbose);
RcppExport SEXP _QuickBLAST_SetQuickBLASTOptions(SEXP ptrSEXP, SEXP program_nameSEXP, SEXP optionsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type program_name(program_nameSEXP);
    Rcpp::traits::input_parameter< SEXP >::type options(optionsSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(SetQuickBLASTOptions(ptr, program_name, options, verbose));
    return rcpp_result_gen;
END_RCPP
}
// BLAST2Seqs
RcppExport SEXP BLAST2Seqs(SEXP ptr, SEXP query, SEXP subject, bool verbose);
RcppExport SEXP _QuickBLAST_BLAST2Seqs(SEXP ptrSEXP, SEXP querySEXP, SEXP subjectSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type query(querySEXP);
    Rcpp::traits::input_parameter< SEXP >::type subject(subjectSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(BLAST2Seqs(ptr, query, subject, verbose));
    return rcpp_result_gen;
END_RCPP
}
// BLAST2Folders
RcppExport bool BLAST2Folders(SEXP ptr, SEXP query, SEXP subject, SEXP extension, SEXP out_folder, SEXP out_format, unsigned int num_threads, bool reciprocal_hits, unsigned int min_batch_size, bool verbose);
RcppExport SEXP _QuickBLAST_BLAST2Folders(SEXP ptrSEXP, SEXP querySEXP, SEXP subjectSEXP, SEXP extensionSEXP, SEXP out_folderSEXP, SEXP out_formatSEXP, SEXP num_threadsSEXP, SEXP reciprocal_hitsSEXP, SEXP min_batch_sizeSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type query(querySEXP);
    Rcpp::traits::input_parameter< SEXP >::type subject(subjectSEXP);
    Rcpp::traits::input_parameter< SEXP >::type extension(extensionSEXP);
    Rcpp::traits::input_parameter< SEXP >::type out_folder(out_folderSEXP);
    Rcpp::traits::input_parameter< SEXP >::type out_format(out_formatSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type num_threads(num_threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type reciprocal_hits(reciprocal_hitsSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type min_batch_size(min_batch_sizeSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(BLAST2Folders(ptr, query, subject, extension, out_folder, out_format, num_threads, reciprocal_hits, min_batch_size, verbose));
    return rcpp_result_gen;
END_RCPP
}
// BLAST1Folder
RcppExport bool BLAST1Folder(SEXP ptr, SEXP input_folder, SEXP extension, SEXP out_folder, SEXP out_format, unsigned int num_threads, bool reciprocal_hits, unsigned int min_batch_size, bool verbose);
RcppExport SEXP _QuickBLAST_BLAST1Folder(SEXP ptrSEXP, SEXP input_folderSEXP, SEXP extensionSEXP, SEXP out_folderSEXP, SEXP out_formatSEXP, SEXP num_threadsSEXP, SEXP reciprocal_hitsSEXP, SEXP min_batch_sizeSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type input_folder(input_folderSEXP);
    Rcpp::traits::input_parameter< SEXP >::type extension(extensionSEXP);
    Rcpp::traits::input_parameter< SEXP >::type out_folder(out_folderSEXP);
    Rcpp::traits::input_parameter< SEXP >::type out_format(out_formatSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type num_threads(num_threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type reciprocal_hits(reciprocal_hitsSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type min_batch_size(min_batch_sizeSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(BLAST1Folder(ptr, input_folder, extension, out_folder, out_format, num_threads, reciprocal_hits, min_batch_size, verbose));
    return rcpp_result_gen;
END_RCPP
}
// BLAST2Files
RcppExport SEXP BLAST2Files(SEXP ptr, SEXP query, SEXP subject, SEXP out_file, SEXP out_format, unsigned int num_threads, bool return_values, unsigned int min_batch_size, bool verbose);
RcppExport SEXP _QuickBLAST_BLAST2Files(SEXP ptrSEXP, SEXP querySEXP, SEXP subjectSEXP, SEXP out_fileSEXP, SEXP out_formatSEXP, SEXP num_threadsSEXP, SEXP return_valuesSEXP, SEXP min_batch_sizeSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type query(querySEXP);
    Rcpp::traits::input_parameter< SEXP >::type subject(subjectSEXP);
    Rcpp::traits::input_parameter< SEXP >::type out_file(out_fileSEXP);
    Rcpp::traits::input_parameter< SEXP >::type out_format(out_formatSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type num_threads(num_threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type return_values(return_valuesSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type min_batch_size(min_batch_sizeSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(BLAST2Files(ptr, query, subject, out_file, out_format, num_threads, return_values, min_batch_size, verbose));
    return rcpp_result_gen;
END_RCPP
}
// RemoteBLAST
RcppExport SEXP RemoteBLAST(SEXP ptr, SEXP database, SEXP query_input, int input_type, SEXP outFile, SEXP outFormat, bool return_values, unsigned int max_poll_seconds, unsigned int poll_interval_ms, bool verbose);
RcppExport SEXP _QuickBLAST_RemoteBLAST(SEXP ptrSEXP, SEXP databaseSEXP, SEXP query_inputSEXP, SEXP input_typeSEXP, SEXP outFileSEXP, SEXP outFormatSEXP, SEXP return_valuesSEXP, SEXP max_poll_secondsSEXP, SEXP poll_interval_msSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type database(databaseSEXP);
    Rcpp::traits::input_parameter< SEXP >::type query_input(query_inputSEXP);
    Rcpp::traits::input_parameter< int >::type input_type(input_typeSEXP);
    Rcpp::traits::input_parameter< SEXP >::type outFile(outFileSEXP);
    Rcpp::traits::input_parameter< SEXP >::type outFormat(outFormatSEXP);
    Rcpp::traits::input_parameter< bool >::type return_values(return_valuesSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type max_poll_seconds(max_poll_secondsSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type poll_interval_ms(poll_interval_msSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(RemoteBLAST(ptr, database, query_input, input_type, outFile, outFormat, return_values, max_poll_seconds, poll_interval_ms, verbose));
    return rcpp_result_gen;
END_RCPP
}
// isBLASTDB
Rcpp::List isBLASTDB(SEXP ptr, SEXP input_db);
RcppExport SEXP _QuickBLAST_isBLASTDB(SEXP ptrSEXP, SEXP input_dbSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type input_db(input_dbSEXP);
    rcpp_result_gen = Rcpp::wrap(isBLASTDB(ptr, input_db));
    return rcpp_result_gen;
END_RCPP
}
// MakeBLASTDB
RcppExport SEXP MakeBLASTDB(SEXP ptr, SEXP input_file, SEXP database_name, bool parse_seqids);
RcppExport SEXP _QuickBLAST_MakeBLASTDB(SEXP ptrSEXP, SEXP input_fileSEXP, SEXP database_nameSEXP, SEXP parse_seqidsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type input_file(input_fileSEXP);
    Rcpp::traits::input_parameter< SEXP >::type database_name(database_nameSEXP);
    Rcpp::traits::input_parameter< bool >::type parse_seqids(parse_seqidsSEXP);
    rcpp_result_gen = Rcpp::wrap(MakeBLASTDB(ptr, input_file, database_name, parse_seqids));
    return rcpp_result_gen;
END_RCPP
}
// BLAST2DBs
RcppExport SEXP BLAST2DBs(SEXP ptr, SEXP query, SEXP subject, SEXP out_file, SEXP out_format, unsigned int num_threads, bool refresh_db, bool return_values, unsigned int min_batch_size, const bool& enable_chunking, unsigned int chunk_size, unsigned int overlap, bool verbose);
RcppExport SEXP _QuickBLAST_BLAST2DBs(SEXP ptrSEXP, SEXP querySEXP, SEXP subjectSEXP, SEXP out_fileSEXP, SEXP out_formatSEXP, SEXP num_threadsSEXP, SEXP refresh_dbSEXP, SEXP return_valuesSEXP, SEXP min_batch_sizeSEXP, SEXP enable_chunkingSEXP, SEXP chunk_sizeSEXP, SEXP overlapSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type query(querySEXP);
    Rcpp::traits::input_parameter< SEXP >::type subject(subjectSEXP);
    Rcpp::traits::input_parameter< SEXP >::type out_file(out_fileSEXP);
    Rcpp::traits::input_parameter< SEXP >::type out_format(out_formatSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type num_threads(num_threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type refresh_db(refresh_dbSEXP);
    Rcpp::traits::input_parameter< bool >::type return_values(return_valuesSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type min_batch_size(min_batch_sizeSEXP);
    Rcpp::traits::input_parameter< const bool& >::type enable_chunking(enable_chunkingSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type chunk_size(chunk_sizeSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type overlap(overlapSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(BLAST2DBs(ptr, query, subject, out_file, out_format, num_threads, refresh_db, return_values, min_batch_size, enable_chunking, chunk_size, overlap, verbose));
    return rcpp_result_gen;
END_RCPP
}
// GetFASTAHeaders
RcppExport SEXP GetFASTAHeaders(const std::string& path, bool keep_gt);
RcppExport SEXP _QuickBLAST_GetFASTAHeaders(SEXP pathSEXP, SEXP keep_gtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type path(pathSEXP);
    Rcpp::traits::input_parameter< bool >::type keep_gt(keep_gtSEXP);
    rcpp_result_gen = Rcpp::wrap(GetFASTAHeaders(path, keep_gt));
    return rcpp_result_gen;
END_RCPP
}
// BLASTFile2DB
RcppExport SEXP BLASTFile2DB(SEXP ptr, SEXP query, SEXP subject, SEXP out_file, SEXP out_format, unsigned int num_threads, bool return_values, unsigned int min_batch_size);
RcppExport SEXP _QuickBLAST_BLASTFile2DB(SEXP ptrSEXP, SEXP querySEXP, SEXP subjectSEXP, SEXP out_fileSEXP, SEXP out_formatSEXP, SEXP num_threadsSEXP, SEXP return_valuesSEXP, SEXP min_batch_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type query(querySEXP);
    Rcpp::traits::input_parameter< SEXP >::type subject(subjectSEXP);
    Rcpp::traits::input_parameter< SEXP >::type out_file(out_fileSEXP);
    Rcpp::traits::input_parameter< SEXP >::type out_format(out_formatSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type num_threads(num_threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type return_values(return_valuesSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type min_batch_size(min_batch_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(BLASTFile2DB(ptr, query, subject, out_file, out_format, num_threads, return_values, min_batch_size));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_QuickBLAST_isQuickBLASTLoaded", (DL_FUNC) &_QuickBLAST_isQuickBLASTLoaded, 0},
    {"_QuickBLAST_RecordBatchVectorToFlattenedDFList", (DL_FUNC) &_QuickBLAST_RecordBatchVectorToFlattenedDFList, 1},
    {"_QuickBLAST_CreateQuickBLASTInstance", (DL_FUNC) &_QuickBLAST_CreateQuickBLASTInstance, 6},
    {"_QuickBLAST_GetInstanceCount", (DL_FUNC) &_QuickBLAST_GetInstanceCount, 0},
    {"_QuickBLAST_GetInstanceID", (DL_FUNC) &_QuickBLAST_GetInstanceID, 1},
    {"_QuickBLAST_GetQuickBLASTInstance", (DL_FUNC) &_QuickBLAST_GetQuickBLASTInstance, 1},
    {"_QuickBLAST_DeleteQuickBLASTInstance", (DL_FUNC) &_QuickBLAST_DeleteQuickBLASTInstance, 1},
    {"_QuickBLAST_GetQuickBLASTOptions", (DL_FUNC) &_QuickBLAST_GetQuickBLASTOptions, 1},
    {"_QuickBLAST_SetQuickBLASTOptions", (DL_FUNC) &_QuickBLAST_SetQuickBLASTOptions, 4},
    {"_QuickBLAST_BLAST2Seqs", (DL_FUNC) &_QuickBLAST_BLAST2Seqs, 4},
    {"_QuickBLAST_BLAST2Folders", (DL_FUNC) &_QuickBLAST_BLAST2Folders, 10},
    {"_QuickBLAST_BLAST1Folder", (DL_FUNC) &_QuickBLAST_BLAST1Folder, 9},
    {"_QuickBLAST_BLAST2Files", (DL_FUNC) &_QuickBLAST_BLAST2Files, 9},
    {"_QuickBLAST_RemoteBLAST", (DL_FUNC) &_QuickBLAST_RemoteBLAST, 10},
    {"_QuickBLAST_isBLASTDB", (DL_FUNC) &_QuickBLAST_isBLASTDB, 2},
    {"_QuickBLAST_MakeBLASTDB", (DL_FUNC) &_QuickBLAST_MakeBLASTDB, 4},
    {"_QuickBLAST_BLAST2DBs", (DL_FUNC) &_QuickBLAST_BLAST2DBs, 13},
    {"_QuickBLAST_GetFASTAHeaders", (DL_FUNC) &_QuickBLAST_GetFASTAHeaders, 2},
    {"_QuickBLAST_BLASTFile2DB", (DL_FUNC) &_QuickBLAST_BLASTFile2DB, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_QuickBLAST(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
