# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Stub function that always returns true. Only to test the connection of DLLs and C function calls
#' @examples
#' \dontrun{
#' QuickBLAST::isQuickBLASTLoaded()
#' }
#'
#' @return Always TRUE
#' @md
#' @export
isQuickBLASTLoaded <- function() {
    .Call(`_QuickBLAST_isQuickBLASTLoaded`)
}

#' @export
GetInstanceCount <- function() {
    .Call(`_QuickBLAST_GetInstanceCount`)
}

#' @name CreateNewBLASTInstance
#'
#' @title Create new BLAST instance with seq_type, strand, program and BLAST options.
#'
#' @description Create a new QuickBLAST C++ object with seq_type, strand, program and BLAST options, which can be used in QuickBLAST::BLAST2Files() and QuickBLAST::BLAST2Seqs()
#'
#' @param seq_info (R List) list((int) "seq_type" : 0 - (eNucleotide) (OR) 1 - (eProtein), (int) "strand" = 0 - (ePlus) (OR) 1 - (eMinus), (bool) "save_sequences" = Save Sequences in the arrow::RecordBatch?). Named or unnamed List is accepted but in order.
#' @param program (string) Name of the BLAST program
#' @param options (string (or) Named List) List of BLAST options - check QuickBLAST::GetAvailableBLASTOptions()
#' @return C++ Pointer of QuickBLAST Object (Cannot be used in R)
#' @export
#' @useDynLib QuickBLAST, .registration = TRUE, .fixes="QB_"
CreateNewBLASTInstance <- function(seq_info, program, options) {
    .Call(`_QuickBLAST_CreateNewBLASTInstance`, seq_info, program, options)
}

