# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name isQuickBLASTLoaded
#' @title Check R <-> C++ (FFI) connection
#'
#' @description This function does nothing than check the connection between the R package and C++ libraries
#'
#' @return String that successfully confirms when the package is loaded properly
#' @export
isQuickBLASTLoaded <- function() {
    .Call(`_QuickBLAST_isQuickBLASTLoaded`)
}

